Enhancement: Enable no_trailing_comma_in_singleline_array fixer
FakerPHP/Faker pull request #214
Opened 2020-12-21 21:41 UTC by localheinz

This PR

* [x] enables the `no_trailing_comma_in_singleline_array` fixer
* [ ] runs `make cs`

Follows #157.

💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.2/doc/rules/array_notation/no_trailing_comma_in_singleline_array.rst.

2020-12-21 21:54 UTC, GrahamCampbell requested changes
👎 waste of time

2020-12-21 22:34 UTC, pimjansen approved these changes

2020-12-21 22:34 UTC, pimjansen commented
@localheinz needs quick rebase

2020-12-21 22:35 UTC, localheinz commented
@pimjansen 

Will get to it tomorrow - have a good night!

2020-12-22 09:32 UTC, pimjansen approved these changes

2020-12-22 09:32 UTC, merged

2020-12-22 09:33 UTC, localheinz commented
Thank you, @pimjansen!