Enhancement: Enable and configure global_namespace_import fixer
FakerPHP/Faker pull request #216
Opened 2020-12-21 21:50 UTC by localheinz

This PR

* [x] enables and configures the `global_namespace_import` fixer
* [ ] runs `make cs`

Follows #157.

💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.17.2/doc/rules/import/global_namespace_import.rst.

2020-12-21 21:53 UTC, localheinz commented on src/Faker/ORM/Propel/ColumnTypeGuesser.php
> -use PropelColumnTypes;
❓

2020-12-21 21:54 UTC, GrahamCampbell requested changes
👎 waste of time

2020-12-21 22:34 UTC, pimjansen commented on src/Faker/ORM/Propel/ColumnTypeGuesser.php
> -use PropelColumnTypes;
Wth didnt even knew these

2020-12-23 17:49 UTC, pimjansen approved these changes

2020-12-23 17:49 UTC, merged

2020-12-23 18:29 UTC, localheinz commented
Thank you, @pimjansen!