Adding jcb credit card
FakerPHP/Faker pull request #22
Opened 2020-10-28 07:57 UTC by mihaileu

2020-10-28 07:59 UTC, pimjansen commented
There are changes done that should not be there. Also the build is failing @mihaileu

2020-10-28 08:15 UTC, mihaileu commented
Yeah I see. It was initially forked from original repo and somehow contains more code. I'll come back with the proper PR's as seems the old ones are not ok

2020-10-28 11:29 UTC, pimjansen commented
@mihaileu will you update these PRs or whats the plan?

2020-10-28 11:33 UTC, mihaileu commented
Yes, not now but today I hope.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Pim Jansen <notifications@github.com>
Sent: Wednesday, October 28, 2020 1:29:37 PM
To: FakerPHP/Faker <Faker@noreply.github.com>
Cc: mihaileu <mihai.leu@hotmail.com>; Mention <mention@noreply.github.com>
Subject: Re: [FakerPHP/Faker] Adding jcb credit card (#22)


@mihaileu<https://github.com/mihaileu> will you update these PRs or whats the plan?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/FakerPHP/Faker/pull/22#issuecomment-717872620>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AM6RUZI26KCGOLN7FXEBXS3SM76CDANCNFSM4TB6TPIA>.

2020-10-28 20:06 UTC, chris-doehring requested changes

2020-10-28 20:06 UTC, chris-doehring commented on src/Faker/Provider/Payment.php
> +     * @param string $type      Supporting any of 'Visa', 'MasterCard', 'American Express', and 'Discover'
```suggestion
     * @param string $type      Supporting any of 'Visa', 'MasterCard', 'American Express', 'Discover' and 'JCB'
```

2020-10-30 07:52 UTC, Nyholm commented
Could you please revert the unrelated CS changes.

2020-11-27 08:24 UTC, bramceulemans commented
There seem to be conflicts. Can you please rebase onto main and revert the code style changes (`array()` to `[ ]`, etc.)?

2020-12-09 23:38 UTC, closed without merging