Added a note about our BC promise
FakerPHP/Faker pull request #273
Opened 2021-01-30 14:22 UTC by Nyholm

We should clearly state what is included and what is not included in our BC promise.

2021-01-30 14:50 UTC, GrahamCampbell commented
This should go in the contribution guide. In fact, I think some of this already is?

2021-01-30 18:16 UTC, pimjansen commented
Shouldnt we add it in both? Since it will also be relevant for regular use that will just consume only

2021-01-30 18:16 UTC, Nyholm commented
Oh. Is it? It really shouldn't be there. :)

It is a promise to all our users. Not just the contributors. 

I'll update the PR

2021-01-30 22:05 UTC, bramceulemans commented
The addition of this section looks good to me.

2021-01-30 22:05 UTC, bramceulemans approved these changes

2021-01-30 22:08 UTC, bramceulemans requested changes

2021-01-30 22:08 UTC, bramceulemans commented on README.md
> +Classes marked as `@experimental` or `@internal` is not included in the BC promise.
```suggestion
Classes marked as `@experimental` or `@internal` are not included in our backward compatibility promise.
```

2021-01-31 14:04 UTC, pimjansen commented
Lgtm except the comment of bram

2021-02-04 09:49 UTC, bramceulemans approved these changes

2021-02-04 09:51 UTC, merged