Make the special generators compatible with static analysis
FakerPHP/Faker pull request #348
Opened 2021-07-08 15:26 UTC by stof

### What is the reason for this PR?

As those generators are re-exposing the Generator API through magic methods, this makes static analyzers know about it thanks to the mixin annotation.
Prior to 1.15, the generator methods were documented as returning Generator instead of those special generators to make methods available, but that was lying about the actual type (which would break typehints).

- [ ] A new feature
- [x] Fixed an issue (resolve https://github.com/FakerPHP/Faker/pull/307#issuecomment-876501573)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

2021-07-08 18:56 UTC, bramceulemans requested changes
Even though they are in the same package, I think it would be good for readability to add the FQDN here.

2021-07-09 08:26 UTC, stof commented
@bramceulemans why ? `@mixin` works with relative names, like all other phpdoc tags

2021-07-09 08:27 UTC, bramceulemans commented
> @bramceulemans why ? `@mixin` works with relative names, like all other phpdoc tags

When someone is reading a class file on it's own, it's easier to see where the mixin is located without scrolling up to the namespace.

2021-07-09 08:30 UTC, stof commented
@bramceulemans that argument would apply even more to `@return` (here the `@mixin` is 5 lines below the namespace, not 50, so there might not even a need to scroll up). And this project does not require using FQCN in all places of the code (typehints, phpdoc, return types, etc...).

2021-07-09 08:35 UTC, bramceulemans commented
You're right, good argument. Have a nice day! MERGED!

2021-07-09 08:35 UTC, bramceulemans approved these changes

2021-07-09 08:35 UTC, merged

2021-07-09 08:54 UTC, stof commented
@bramceulemans any chance to tag a 1.15.1 release with this fix ? This would avoid having to ignore errors in phpstan about methods not existing in UniqueGenerator.

2021-07-22 13:19 UTC, stof commented
@bramceulemans any chance to tag a release ?

2021-07-22 14:38 UTC, pimjansen commented
> @bramceulemans any chance to tag a release ?

Will go later as 1.16