Add E164 Ukrainian phone numbers
FakerPHP/Faker pull request #357
Opened 2021-08-01 16:26 UTC by punyflash

### What is the reason for this PR?

I was in need to work with a large amount of fake Ukrainian phone numbers and noticed that generated numbers was international. The reason is - E164 formats was not overrided from base phone provider.

- [x] A new feature
- [ ] Fixed an issue (resolve #ID)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

Overrided `$e164Formats` for `Faker\Provider\uk_UA\PhoneNumber` to give only Ukrainian phone numbers.

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

2021-08-01 19:09 UTC, pimjansen commented
Do we have some source for the formats? Missing these

2021-08-01 19:52 UTC, punyflash commented
Source formats described here https://www.itu.int/oth/T02020000DB/en

2021-08-01 20:51 UTC, pimjansen commented
> Source formats described here https://www.itu.int/oth/T02020000DB/en

Please add to the code itself so we have a valid ref for later

2021-08-02 16:31 UTC, pimjansen requested changes

2021-08-02 16:31 UTC, pimjansen commented on src/Faker/Provider/uk_UA/PhoneNumber.php
> +
Useless whitespace

2021-08-02 16:31 UTC, pimjansen commented on test/Faker/Provider/uk_UA/PhoneNumberTest.php
> +        $pattern = "/^\+?380[1-9]\d{8}$/";
Please use single quotes instead

2021-08-02 16:31 UTC, pimjansen commented
To small things. For the rest it looks good to me

2021-08-04 16:00 UTC, pimjansen approved these changes
Thanks!

2021-08-04 16:00 UTC, merged