Added provider of Albania
FakerPHP/Faker pull request #419
Opened 2022-01-16 17:38 UTC by notaprodev

### What is the reason for this PR?

- [ ] A new feature
- [ ] Fixed an issue (resolve #ID)

### Author's checklist

- [ ] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [ ] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

2022-01-16 17:44 UTC, pimjansen commented
I see a lot of copy paste from other locales. There are docs for italian wikipedia pages?

Please add reference to sources of all of the data

2022-01-16 18:54 UTC, notaprodev commented
thanks for the fast replay. I will fix the mentioned problems

2022-01-16 20:59 UTC, pimjansen requested changes
I added a few comments but please have a look at this locale since quality wise it is far from good.

2022-01-16 20:59 UTC, pimjansen commented on src/Faker/Provider/sq_AL/Address.php
> +    protected static $country = [
These are not localized

2022-01-16 20:59 UTC, pimjansen commented on src/Faker/Provider/sq_AL/Address.php
> +        '{{cityPrefix}} {{firstName}} {{citySuffix}}',
Firstnames in a city name is odd?

2022-01-16 20:59 UTC, pimjansen commented on src/Faker/Provider/sq_AL/Address.php
> +    protected static $streetNameFormats = [
Firstnames in street names?

2022-01-16 20:59 UTC, pimjansen commented on src/Faker/Provider/sq_AL/Address.php
> +https://en.youbianku.com/albania
This is not how we define sources, see other locales

2022-01-16 20:59 UTC, pimjansen commented on src/Faker/Provider/sq_AL/Company.php
> +        '{{lastName}} {{companySuffix}}',
Lastnames for companies?

2022-01-16 20:59 UTC, pimjansen commented on src/Faker/Provider/sq_AL/Company.php
> +    protected static $companySuffix = ['ShPK', 'ShA', 'Group'];
Missing source

2022-01-16 20:59 UTC, pimjansen commented on src/Faker/Provider/sq_AL/Payment.php
> +    /*
This is not a valid phpdoc

2022-01-16 20:59 UTC, pimjansen commented on src/Faker/Provider/sq_AL/Person.php
> +    protected static $firstNameMale = [
No sources and wrong indent

2022-01-16 20:59 UTC, pimjansen commented on src/Faker/Provider/sq_AL/Person.php
> +    protected static $firstNameFemale = [
No sources

2022-01-16 20:59 UTC, pimjansen commented on src/Faker/Provider/sq_AL/Person.php
> +    protected static $lastName = [
No sources

2022-01-16 20:59 UTC, pimjansen commented on src/Faker/Provider/sq_AL/PhoneNumber.php
> +/* https://en.wikipedia.org/wiki/Telephone_numbers_in_Albania
Not a valid position

2022-01-17 07:10 UTC, GlennM commented
This is marked as "a new feature", but in the Contribution Guide it is mentioned that:
"_At the moment we are not looking for pull requests that add new features. We are planning for Faker 2.0's architecture._"

Are there any updates on the progress of the [new architecture](https://github.com/FakerPHP/Faker/discussions/15)?

2022-01-17 17:54 UTC, pimjansen commented
> This is marked as "a new feature", but in the Contribution Guide it is mentioned that:
> 
> "_At the moment we are not looking for pull requests that add new features. We are planning for Faker 2.0's architecture._"
> 
> 
> 
> Are there any updates on the progress of the [new architecture](https://github.com/FakerPHP/Faker/discussions/15)?

You are right. Overall indeed we do no accept new changes that could affect this but i am not against. It only means later that all these changes are gone where the locales will be moved away from the Faker core itself.

There are still some issues at this moment on the modifiers and stacking them. If all that is there we will setup the default english language pack and start on some others from the core dev team as well.

2022-01-17 17:55 UTC, pimjansen commented
Im going to stop the PR here. It is a new change which is not matching the contribution guide. Also the quality is far from good where we rather but the limited time we have in future development

2022-01-17 17:55 UTC, closed without merging

2022-01-17 18:35 UTC, notaprodev commented
I am sorry I marked it as new feature. Can you please point what is the problem

2022-01-18 09:39 UTC, bram-pkg commented
Hi @notaprodev,

The main problem is that this is adding new functionality (in the form of a new provider).
Secondary, the quality and attention to detail in this PR is not up to par with the rest of our codebase. I have left you some comments on the code, to explain this further.

2022-01-18 09:45 UTC, bram-pkg commented on src/Faker/Provider/sq_AL/Address.php
> +
Spacing here?

2022-01-18 09:45 UTC, bram-pkg commented on src/Faker/Provider/sq_AL/Address.php
> +     * @see https://en.wikipedia.org/wiki/Foreign_relations_of_Albania
This is a list of English country names, from English wikipedia. Not localized into Albanian.

2022-01-18 09:45 UTC, bram-pkg commented on src/Faker/Provider/sq_AL/Address.php
> +}
No newline

2022-01-18 09:45 UTC, bram-pkg commented on src/Faker/Provider/sq_AL/Internet.php
> +    protected static $freeEmailDomain = ['gmail.com', 'yahoo.com', 'hotmail.com'];
No point in having these for a specific locale, either add specific Albanian domains or remove this.

2022-01-18 09:45 UTC, bram-pkg commented on src/Faker/Provider/sq_AL/Person.php
> +
Spacing

2022-01-18 09:45 UTC, bram-pkg commented on src/Faker/Provider/sq_AL/Person.php
> +    /**
Spacing

2022-01-18 09:45 UTC, bram-pkg commented on src/Faker/Provider/sq_AL/Person.php
> +
Spacing

2022-01-18 09:45 UTC, bram-pkg commented on src/Faker/Provider/sq_AL/Address.php
> +        'Afganistan', 'Algjeria', 'American Samoa', 'Andorra', 'Angola','Antartide (territori a sud del 60° parallelo)', 'Argjentina', 'Armenia',
Spacing in this array is inconsistent.