Make Singapore Person class extends from Malaysia Person class to inherits its names methods
FakerPHP/Faker pull request #507
Opened 2022-08-15 15:05 UTC by ziming

Currently Singapore Person class has no name related methods, which mean that when you call

$this->faker->name()

you will get either Jane Doe or John Doe, this also cause issues when you do $this->faker->unique()->name()

since you only have 2 names in the default Person super class.

Now, Malaysia and Singapore are 2 neighbour countries that share many similarities when it come to person names. Making it a great class for the Singapore Person class to inherit from.

The alternative would be for me to copy for the name related methods and variables from the Malaysia Person class over to the Singapore Person class, but that is a lot of code and duplication so I thought extend would be a better option hence this PR.

2022-08-16 05:58 UTC, pimjansen commented
This does not feel right. Both belong to another language so please lets not mix in between. If you want proper names, update the pr to reflect it in the locale itself

2022-08-16 07:43 UTC, ziming commented
so ur fine with me copying all the name related methods and variables over?

or can I hold an instance of the Malaysia person class in the singapore person class and proxy calls to it?

2022-08-16 07:52 UTC, pimjansen commented
> so ur fine with me copying all the name related methods and variables over? which is pretty much everything except the malaysian Id method
> 
> or can I hold an instance of the Malaysia person class in the singapore person class and proxy calls to it?
> 
> let me know which u prefer and I update the pr

Copy it over since both are seperate languages. For Faker 2.x which is the next major all will consist of language packs so there cant be a mix between those

2022-08-16 08:27 UTC, ziming commented
Alright, I have copied them over.

2022-08-16 19:52 UTC, pimjansen commented
Please update the PR according the contribution guidelines. I see no tests at all etc

2022-08-16 22:32 UTC, ziming commented
oh ok I will copy the tests over too later

2022-08-17 07:50 UTC, pimjansen commented
> oh ok I will copy the tests over too later. am sick now

Fine, but also please review the test to see if they are valid. We will review this as new code

2022-08-17 10:41 UTC, ziming commented
Hi

I just went to the ms_MY Person test file and found that it has no test for it's name methods

https://github.com/FakerPHP/Faker/blob/main/test/Faker/Provider/ms_MY/PersonTest.php

I then went to check a few other related locales since Singapore and Malaysia is largely made up of (Chinese, Malays, Indians, English).

English: (no name tests)
https://github.com/FakerPHP/Faker/blob/main/test/Faker/Provider/en_US/PersonTest.php

https://github.com/FakerPHP/Faker/blob/main/test/Faker/Provider/en_GB/PersonTest.php

Chinese: (no name tests)
https://github.com/FakerPHP/Faker/blob/main/test/Faker/Provider/zh_TW/PersonTest.php

Malay: (no name tests)
https://github.com/FakerPHP/Faker/blob/main/test/Faker/Provider/ms_MY/PersonTest.php

Indian: (no name tests)
https://github.com/FakerPHP/Faker/tree/main/test/Faker/Provider/en_IN

So this mean i have to try write my own tests for the names, which will take longer, hope you don't mind waiting until my covid is over. So it may take longer than this week.

2022-08-17 16:56 UTC, pimjansen commented
No worries! Better to have solid code. Will pin the PR for the time being

2022-08-31 08:15 UTC, ziming commented
Hi, added the tests.

2022-09-03 14:40 UTC, ziming commented
Hmm I should have used assertIsString instead of assertNotEmpty for some of them

2022-09-10 04:23 UTC, ziming commented
Hi @pimjansen I changed the assertion for those where the result might be empty string to assertIsString

2022-09-21 05:35 UTC, ziming commented
Hi @pimjansen anything else I need to do?

Thank you

2022-09-21 07:25 UTC, pimjansen commented
I did not look yet, currently kn leave but i will review once im back

2022-11-04 16:14 UTC, ziming commented
hi @pimjansen hope u enjoyed ur leave. is this okay now?

2022-12-05 15:29 UTC, bram-pkg commented
For some reason the pipeline is not running.

2023-01-09 06:13 UTC, ziming commented
Anything I can do to help resolve that or is that something on the faker team side?

2023-03-22 11:19 UTC, bram-pkg commented
You could try making an empty commit.

2023-05-14 12:38 UTC, ziming commented
As you can see I tried to make an empty commit but the github actions still did not run

2023-05-14 15:31 UTC, DvDty commented
Seems like the pipeline jobs are queued, but are "awaiting approval from a maintainer"?
Example: https://github.com/FakerPHP/Faker/actions/runs/4766832639

2023-05-14 15:52 UTC, aznj approved these changes

2023-05-14 17:57 UTC, bram-pkg commented
![image](https://github.com/FakerPHP/Faker/assets/13304739/59d270b1-0efc-4509-84b7-3914529b6a7f)
I do not see an admin approval button.

Please fix the tests for PHP 7.4 and the other pipeline actions

2023-05-14 18:30 UTC, pimjansen commented
> ![image](https://github.com/FakerPHP/Faker/assets/13304739/59d270b1-0efc-4509-84b7-3914529b6a7f)
> 
> I do not see an admin approval button.
> 
> 
> 
> Please fix the tests for PHP 7.4 and the other pipeline actions

I approved whehe

2023-06-09 11:35 UTC, pimjansen requested changes
See my review changes on the tests

2023-06-09 11:35 UTC, pimjansen commented on test/Faker/Provider/en_SG/PersonTest.php
> +        self::assertNotEmpty(Person::firstNameMaleMalay());
They will never be empty due to how interfacing works. Please assert actual values with seeding instead.

2024-11-09 18:12 UTC, closed without merging