Fix PHP 8.2 warning: Use self::class . '::[…]' instead of 'static::[…]' for callbacks
FakerPHP/Faker pull request #570
Opened 2022-12-10 21:25 UTC by MyIgel

### What is the reason for this PR?

This implements remaining changes for #479 (Use of "static" in callables is deprecated in PHP 8.2) and is an extension of #528 (Ensure php 8.2 compatibility)

- [ ] Fixed PHP 8.2 warnings (should resolve the #479 issue?)

### Author's checklist

- [x] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [x] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io) (there are none)

### Summary of changes
Use self::class . '::[…]' instead of 'static::[…]' on callbacks which triggered a PHP 8.2 warning. Implementation analogous to [php.watch](https://php.watch/versions/8.2/partially-supported-callable-deprecation#deprecated-patterns).

The phpstan "errors" can be ignored as that functionality still works for PHP 7.4 and is thus added to ignoreErrors.

### Review checklist

- [ ] All checks have passed
- [ ] Changes are approved by maintainer

2022-12-10 21:26 UTC, MyIgel commented
I guess the `BC Check / Roave BC Check` can be ignored? :D

2022-12-10 21:27 UTC, localheinz commented
@MyIgel 

Yes, we are waiting for someone (perhaps @Nyholm) to fix this issue.

2022-12-10 21:35 UTC, GrahamCampbell requested changes

2022-12-10 21:35 UTC, GrahamCampbell commented on src/Faker/Provider/Base.php
> +    private static function replaceWildcard($string, $wildcard = '#', $callback = self::class . '::randomDigit')
static::class may do the right thing, however

2022-12-10 21:43 UTC, localheinz requested changes
Can you also apply this diff?

```diff
diff --git a/phpunit.xml.dist b/phpunit.xml.dist
index 1c521356..37222a4f 100644
--- a/phpunit.xml.dist
+++ b/phpunit.xml.dist
@@ -13,7 +13,7 @@
         <listener class="Symfony\Bridge\PhpUnit\SymfonyTestsListener"/>
     </listeners>
     <php>
-        <env name="SYMFONY_DEPRECATIONS_HELPER" value="max[self]=404"/>
+        <env name="SYMFONY_DEPRECATIONS_HELPER" value="max[self]=0"/>
     </php>
     <testsuites>
         <testsuite name="Faker Test Suite">
```

2022-12-10 21:43 UTC, localheinz commented on src/Faker/Provider/Base.php
> +    private static function replaceWildcard($string, $wildcard = '#', $callback = self::class . '::randomDigit')
```suggestion
    private static function replaceWildcard($string, $wildcard = '#', $callback = static::class . '::randomDigit')
```

2022-12-10 21:43 UTC, localheinz commented on src/Faker/Provider/Base.php
> +        $string = self::replaceWildcard($string, '%', self::class . '::randomDigitNotNull');
```suggestion
        $string = self::replaceWildcard($string, '%', static::class . '::randomDigitNotNull');
```

2022-12-10 21:43 UTC, localheinz commented on src/Faker/Provider/Base.php
> +        return self::replaceWildcard($string, '?', self::class . '::randomLetter');
```suggestion
        return self::replaceWildcard($string, '?', static::class . '::randomLetter');
```

2022-12-10 21:43 UTC, localheinz commented on src/Faker/Provider/Base.php
> +        return preg_replace_callback('/\*/u', self::class . '::randomAscii', $string);
```suggestion
        return preg_replace_callback('/\*/u', static::class . '::randomAscii', $string);
```

2022-12-10 21:43 UTC, localheinz commented on src/Faker/Provider/Base.php
> +        $regex = preg_replace_callback('/\\\d/', self::class . '::randomDigit', $regex);
```suggestion
        $regex = preg_replace_callback('/\\\w/', static::class . '::randomLetter', $regex);
        $regex = preg_replace_callback('/\\\d/', static::class . '::randomDigit', $regex);
```

2022-12-10 21:43 UTC, localheinz commented on src/Faker/Provider/en_CA/Address.php
> +        $string = preg_replace_callback('/\?/u', self::class . '::randomPostcodeLetter', $string);
```suggestion
        $string = preg_replace_callback('/\#/u', static::class . '::randomDigit', $string);
        $string = preg_replace_callback('/\?/u', static::class . '::randomPostcodeLetter', $string);
```

2022-12-10 22:03 UTC, localheinz commented on src/Faker/Provider/Base.php
> +    private static function replaceWildcard($string, $wildcard, $callback)
Method is `private` and always invoked with arguments for all parameters - no need for default values.

Also see #571.

2022-12-10 22:03 UTC, MyIgel commented on src/Faker/Provider/Base.php
> +    private static function replaceWildcard($string, $wildcard = '#', $callback = self::class . '::randomDigit')
Thats a better solution  :D

2022-12-10 22:04 UTC, localheinz approved these changes

2022-12-10 22:08 UTC, MyIgel commented
I guess the changes should be squashed on merge? :D

2022-12-13 09:12 UTC, merged

2022-12-13 09:12 UTC, localheinz commented
Thank you, @GrahamCampbell and @MyIgel!