fix: Generate valid BIC/SWIFT numbers (#902)
FakerPHP/Faker pull request #921
Opened 2024-12-08 20:51 UTC by vjandrea

### What is the reason for this PR?

- [ ] A new feature
- [X] Fixed an issue (#902)

### Author's checklist

- [X] Follow the [Contribution Guide](https://github.com/FakerPHP/Faker/blob/main/.github/CONTRIBUTING.md)
- [X] New features and changes are [documented](https://github.com/FakerPHP/fakerphp.github.io)

### Summary of changes

`swiftBicNumber()` now returns SWIFT/BIC numbers that pass validation.
Added a dev requirement for symfony/validator that might be used for other generators as well.

### Review checklist

- [ ] All checks have passed
- [ ] Changes are added to the `CHANGELOG.md`
- [ ] Changes are approved by maintainer

2024-12-09 06:56 UTC, pimjansen commented
Im not a fan of just adding new packages to the base of Faker

2024-12-09 09:09 UTC, vjandrea commented
I see, I will refactor the test to be package agnostic.

2024-12-12 19:30 UTC, vjandrea commented
@pimjansen I removed the extra dependencies, do you mind to review please?

2025-02-20 10:07 UTC, pimjansen requested changes

2025-02-20 10:07 UTC, pimjansen commented on test/Faker/Provider/PaymentTest.php
> +
Missing test for an invalid country code

2025-02-20 10:07 UTC, pimjansen commented on src/Faker/Provider/Payment.php
> +    public static function swiftBicNumber($countryCode = null)
This is a bit shady since you have no clue what can be put in here and all can be invalid. I think we have a list of all country codes already in the package. Can you use that to verify it exists?

2025-05-06 01:47 UTC, closed without merging